
services:

  traefik:
    image: "traefik:v3.1"
    container_name: "traefik"
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    environment:
      DOMAIN_NAME: ${DOMAIN_NAME}
    networks:
      - traefik-network
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./volumes/traefik/letsencrypt:/letsencrypt"
      - "./volumes/traefik/traefik.yml:/etc/traefik/traefik.yml:ro"
      - "./volumes/traefik/dynamic:/dynamic:ro"
    healthcheck:
      test: "nc -zv 127.0.0.1 80 && nc -zv 127.0.0.1 443 && nc -zv 127.0.0.1 8080"
      interval: 1s
      timeout: 1s
      retries: 15

networks:
  traefik-network:
    driver: bridge